### ISSUE TITLE
cart-list.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [isokyrka-clgx/shop#4]
Попробуйте этот код вынести в директиву

`onWheel(event: any) {
    if ((<WheelEvent>event).deltaY > 0) {
      this.renderer.setStyle(this.orderedP.nativeElement, "font-size", "20px");
    } else {
      this.renderer.setStyle(this.orderedP.nativeElement, "font-size", "15px");
    }
  }`

**Comment by isokyrka-clgx** [comment]
Done
